services:

  boilerplate-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ".:/home/app"
    ports:
      - "5050:5050"
    networks:
      - boilerplate-net

networks:
  boilerplate-net:
    driver: bridge
