services:
  boilerplate-server:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - ./.env
    ports:
      - "5050:5050"
    networks:
      - boilerplate-net

networks:
  boilerplate-net:
    driver: bridge
