# ##### SUCCESS #####
CODE_SUCCESS_ADD_TEMPLATE = "SUCCESS_ADD_TEMPLATE"

# ##### ERROR #####
CODE_ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
CODE_ERROR_PYDANTIC = "ERROR_PYDANTIC"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_AUTHENTICATION = "ERROR_AUTHENTICATION"

# ##### NOT #####

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_TEMPLATE = "ALREADY_EXISTS_TEMPLATE"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_TEMPLATE = "NOT_FOUND_TEMPLATE"
